- petl/io/sources.py
When using py.test it redirect stdin/stdout in pseudofiles by
default. Pseudofiles do not provide a fileno() method and as such
raise a `ValueError` as soon as `petl.io.sources` is imported (as shown
below).
```
tests/transform/test_transforms.py:1: in <module>
import petl
../../.virtualenvs/ernie/local/lib/python2.7/site-packages/petl/__init__.py:9: in <module>
from petl import util
../../.virtualenvs/ernie/local/lib/python2.7/site-packages/petl/util/__init__.py:13: in <module>
from petl.util.vis import look, lookall, lookstr, lookallstr, see
../../.virtualenvs/ernie/local/lib/python2.7/site-packages/petl/util/vis.py:12: in <module>
from petl.io.sources import MemorySource
../../.virtualenvs/ernie/local/lib/python2.7/site-packages/petl/io/__init__.py:3: in <module>
from petl.io.sources …
```
> Catches ValueError thrown when sys.stdin is a pseudofile

- optional_requirements.txt
- petl/io/xml.py
I found that the ElementTree library built in to Python did not allow for true XPath support (which meant that I was not able to traverse up from a child row selector to find information about a parent while building a table). This patch allows the optional dependency [lxml](http://lxml.de/) which fully supports XPath (and is a drop-in replacement in most cases for ElementTree, adhering to the API pretty strictly).
> Use lxml if available to enable parent traversal in xml source

- petl/io/db_utils.py
Adds support for named paramstyle.  This is a requirement for the oracle driver cx_Oracle.
> Adds support for named paramstyle

- petl/test/transform/test_selects.py
- petl/transform/selects.py
akin to the stdlib `filter()`, `select()` should choose rows based on the truthiness of the test value rather than its equality to True or False.
> Boolean interpretation of values in select() -> Fix #330

- petl/io/csv_py2.py
- petl/test/io/test_csv_unicode.py
Hi, 
i noticed that Petl tocsv() exports 'None' instead of no value if used with python 2.x. This produces wrong values if data is exported and re-loaded from csv.
Could we change that the unicode encoding is only applied for not-None values?
> Petl.tocsv() expots 'None' string instead of no value

- petl/transform/headers.py
I think this is a useful bit to add to rename()'s doc, especially as it represents a change in default behaviour from 0.x to 1.0.
Cheers,
psj
> add "strict" keyword doc for rename() function

- petl/io/json.py
It's unfortunate to have to listify an incoming generator, but with the current gather-all-keys-for-the-header implementation, the input has to be fully iterated once.
Generator efficiency is still maintained if you pass in a header.
> listify incoming iterable of dicts to fix #341

- petl/io/base.py
`fromdicts()` creates a table with `None` fill if row lengths differ
import petl
dicts = [{"foo": "a", "bar": 1},
{"foo": "b", "bar": 2},
{"bar": 2}]
tbl = petl.fromdicts(dicts)
print(petl.lookall(tbl))
Proposed use of izip_longest (from petl.compat for 2.x/3.x compatibility) yields similar behavior:
import petl
cols = [[0, 1, 2, 3], ['a', 'b', 'c']]
tbl = petl.fromcolumns(cols)
print(petl.lookall(tbl))
> Utilize zip_longest to mirror behavior in fromdicts()

- .travis.yml~
- petl/io/xlsx.py
openpyxl doesn't explicitly close the workbook after you are done iterating it.
This means that if you use petl and then try to rename or move the workbook you get a PermissionError
There's an issue to expose a workbook.close property directly but this will work until then.
https://bitbucket.org/openpyxl/openpyxl/issues/673/close-file-when-done
> make XLSXView close the workbook after iterating

- petl/test/util/test_base.py
- petl/util/base.py
Addresses issue #401 
This method behaves like the get() method of python dictionaries.
Provided a key, it will attempt to fetch the value. If the key does
not exist, it returns a default value. This is None, unless the user
supplies a default value
> Added a get() method to Record

- petl/test/transform/test_validation.py
- petl/transform/validation.py
Adresses issue #399 
If a constraint is optional (has a key,value of optional=True), then
it will only be applied to the table when the table has a field
present to which the constraint applies. Thus, if a constraint is
added for the field 'foo' and that constraint is designated as
optional, then any table checked by the constraint will only have the
constraint applied if the table has a field named 'foo'
> Added ability to make constraints optional

- petl/io/csv.py
- petl/io/csv_py2.py
- petl/io/csv_py3.py
- petl/test/io/test_csv.py
Added an optional header argument to fromcsv/fromtsv to allow
specificying headers for the file instead of taking the first row
> Added support for headerless csv files

- petl/io/xls.py
Clarify what can be used for sheet; it is not immediately obvious without reading the code.
(NO code changes)
> Update fromxls doc string

- .travis.yml
- appveyor.yml
- petl/test/helpers.py
- petl/transform/dedup.py
Modification to fix nosetest helpers.py failing due to changes in Python 3.7 (PEP 479)
nosetests -v and tox -e py27,py36,py37 all passed after modifications.
No new unit tests
No new functions
> Fixed helpers.py for Python 3.7 (PEP 479)

- petl/test/transform/test_regex.py
- petl/transform/regex.py
Added splitdown function (resolves #386).
Added unit test for splitdown function.
Ran `tox -e py26,py27,py36` (I don't have Python 3.4 installed).
Desired results for the example provided in #386 could be accomplished using splitdown followed by split.
Ex.
```
tbl = (('ID', 'AMOUNT', 'RECIPIENT'),
('1', '1000', 'Joe: 25%, Jane: 75%'),
('2', '2000', 'Joe: 25%, Jess: 25%, Jenny: 25%, Jim: 25%'))
actual_step_1 = splitdown(tbl, 'RECIPIENT', ', ')
actual_step_2 = split(actual_step_1, 'RECIPIENT', ': ', newfields=['RECIPIENT', 'PERCENT'])
expect = (('ID', 'AMOUNT', 'RECIPIENT', 'PERCENT'),
('1', '1000', 'Joe', '25%'),
('1', '1000', 'Jane', '75%'),
('2', '2000', 'Joe', '25%'),
('2', '2000', 'Jess', '25%'),
('2', '2000', 'Jenny', '25%'),
('2', '2000', 'Jim', '25%'))
ieq(expect, actual_step_2) …
```
> Add splitdown function

- docs/changes.rst
- docs/io.rst
- optional_requirements.txt
- petl/io/__init__.py
- petl/io/avro.py
- petl/test/io/test_avro.py
- petl/test/io/test_avro_schemas.py
[Apache Avro](https://avro.apache.org/docs/current/spec.html) is a data serialization framework with broad use in many business. 
It is used in data serialization (especially in [Hadoop](https://hadoop.apache.org/) ecosystem), for data exchange for databases ([Redshift](https://aws.amazon.com/redshift/)) and in RPC protocols (like in [Kafka](https://kafka.apache.org/)). 
It has open source libraries to support many languages and generally is faster and safer than text formats like Json, XML or CSV.
Added functions `petl.io.avro.fromavro`, `petl.io.avro.toavro`, and `petl.io.avro.appendavro` for reading and writing to Avro files.
> Added support for reading and writing avro files

- .gitignore
- docs/changes.rst
- docs/io.rst
- optional_requirements.txt
- petl/io/__init__.py
- petl/io/avro.py
- petl/io/codec/__init__.py
- petl/io/codec/lz4.py
- petl/io/codec/xz.py
- petl/io/codec/zstd.py
- petl/io/csv.py
- petl/io/pickle.py
- petl/io/source/__init__.py
- petl/io/source/s3.py
- petl/io/source/smb.py
- petl/io/sources.py
- petl/io/text.py
- petl/test/io/test_codec.py
- petl/test/io/test_source.py
- Refactored url handling in `to...()` and `from...()` functions for allowing dynamic adding sources.
- Added functions `petl.io.sources.register_reader` and `petl.io.sources.register_writer` for registering custom source helpers for handling I/O from remote protocols.
- Added function `petl.io.sources.register_codec` for registering custom helpers for compressing and decompressing files with other algorithms.
- Added classes `petl.io.codec.xz.XZCodec`, `petl.io.codec.xz.LZ4Codec` and `petl.io.codec.zstd.ZstandardCodec` for compressing files with `XZ` and the "state of art"  `LZ4` and `Zstandard` algorithms.
- Added classes :class:`petl.io.source.s3.S3Source` and `petl.io.source.smb.SMBSource` reading and writing files to remote servers using int url the protocols `s3://` and `smb://`.
- …
> add helpers for xz, lz4 and zstandard codec and for s3 and smb remote servers

- optional_requirements.txt
- petl/io/bcolz.py
- petl/io/pytables.py
This is just a quality of life improvement.
Changed docstring for skipping doctests for bcolz and pytables.
It's hard to setup bcolz and pytables because they need local packages installed.
Every time that included code in docstrings they failed leading and one need to erase the docstring for getting the test to pass.
As there is no new features some items don't apply bellow.
> avoid doctest failing when missing bcolz or pytables (hard setup)

- .github/PULL_REQUEST_TEMPLATE.md
This PR has the objetive of improving comunication in PR template.
At least for me. :smile:
1. Improved the pull request template
2. Split items in categories.
3. Added new entries to signaling PR status
> further improve pull request template

- docs/io.rst
- petl/io/remotes.py
- petl/io/sources.py
1. add get_reader() and get_writer() functions for checking if there is a protocol handler
2. when registering with `fsspec` don't override a protocol if the fsspec says that the supporting package is not installed
3. let `fsspec` handle `http` and `https` protocols when `requests` package is installed. This allows using compressions like `zstandard`, `xz`, `lz4`. with this protocols.
> only override protocol with fsspec when support package is installed

- docs/changes.rst
- petl/io/remotes.py
This PR fixes another annoying warning introduced in 1.6.
1. Downgraded unavoidable `warning` to `debug`if `fsspec` is installed but some optional package is not installed.
2. Mentioned in changes.rst
> Downgraded another unavoidable warning to debug

- optional_requirements.txt
- setup.py
This PR has the objective of fixing the build that is not working.
The problem is registered in this [issue](https://github.com/intake/filesystem_spec/issues/366)
1. Added package `aiohttp` to `optional_requirements.txt`
2. Added a `http` optional dependecy in `extra_requires`  in `setup.py`
> fsspec: fixing build and dependencies

- petl/io/avro.py
- petl/test/io/test_avro.py
This PR has the objective of helping the developer figure out what row/record has mismatched data with the Avro schema.
1. Improved exception handling in `toavro()`
2. Added test for exception message
> avro: improve message on schema or data mismatch

- petl/io/__init__.py
- petl/io/xls.py
- petl/io/xlsx.py
- petl/io/xlutils_view.py
- petl/test/io/test_remotes.py
- petl/test/io/test_xlsx.py
This PR is the same as #502 but rebased on top of #506 
1. Added new parameter `mode` to `toxlsx()` from $502
2. Rebased on top of #506
3. Removed a call to `os.path.exists()` as it wont work with remote sources from `fsspec`
> Allow toxlsx() to overwrite add or replace a worksheet

- docs/changes.rst
- optional_requirements.txt
- petl/io/remotes.py
This PR has the objective of fixing a bug when writing to S3.
This is caused by the dependent lib `fsspec` because it has a parameter `auto_mkdir=True` for creating folders automatically.
1. Fixed the `fsspec` call passing `auto_mkdir=False`.
2. This causes the default behavior being of not to create the folders when missing.
> fix exception when writing to S3 with fsspec and auto_mkdir=True

- docs/changes.rst
- petl/io/xlsx.py
- petl/test/io/test_xlsx.py
This PR fixes a problem reported on #514 
1. Added test for fromxlsx(read_only=True)
2. Fixed a bug in fromxlsx with read_only=True
> fix #514: fromxlsx with read_only crashes

- docs/changes.rst
- petl/util/timing.py
This PR has the objective of fix #484 
1. Fixed a compatibility issue with python3.8 in `petl.timings.clock()`
> fix #484: compatibility with python3.8 in petl.timings.clock()

- .travis.yml
- appveyor.yml
- docs/changes.rst
- optional_requirements.txt
- setup.py
- tox.ini
This PR has the objective of building `petl` with python3.8 and python3.9
1. Added new environments `py38` and `py39` to tox.ini.
2. Build with py38 in linux on travis-ci
3. Build with py38 in windows on appveyor
- Package `pandas` doens't build with py39 yet.
- Packages numpy==1.19.2 and Cython==0.29.21 fails to build with py39.
- Can `py39` fix with:
- Cython<0.29.21,>=0.29.13
- numpy<=1.19.2,>=1.16.4
- numexpr<=2.7.1,>=2.6.9
- pandas<=1.1.2,>=0.24.2 ; python_version < '3.9'
> Added py38 and py39 to tox.ini for newer distros

- docs/changes.rst
- petl/io/json.py
Resolves #522 
1. Memory footprint reduced
> Memory Footprint Resolved

- docs/changes.rst
- petl/io/xml.py
- petl/test/io/test_xml.py
This PR has the objective of restricting use of includes in `fromxml()`.
1. Added new parameter `parser` for `fromxml()` for custom parsers.
2. Disabled file includes by default in `fromxml()`
3. Added tests for file inclusion on `fromxml()`
4. Improved the docs about `fromxml()` new parameter.
> Added new parameter parser in fromxml() for custom parsers

- petl/test/helpers.py
- petl/test/io/test_avro.py
- petl/test/io/test_xml.py
This PR has the objective of improving tests.
1. Teached helper `ieq` to handle None
> improve helper ieq() for handling null values

- petl/transform/conversions.py
Fixes #531.
This PR has the objective of... setting in stone the fact that convert() works the way it does by design, not accident.
1. Improved the docs about... petl.transform.conversions.convert() when used with multiple conversions in its whole-row mode.
Adds a doctest. doctests pass; I cannot get the whole test setup working at all, let alone actually test anything.
> Document behavior of multi-field convert-with-row

- docs/changes.rst
- docs/io.rst
- petl/io/__init__.py
- petl/io/xml.py
- petl/test/io/test_xml.py
- tox.ini
This PR has the objective of adding a new function `toxml()`
1. Added new new function `toxml()`
2. Added doc strings for `toxml()`
> Added toxml() as convenience wrapper over totext()

- docs/changes.rst
- petl/test/io/test_xls.py
- petl/test/io/test_xlsx.py
- petl/test/io/test_xml.py
- petl/test/resources/test.xml
This PR has the objective of fixing build failures on conda deployment.
1. Fixed a failure in test_fromxml_url()
2. Fixed a failure in xls/xlsx tests with pkg_resources
> conda: fixing packaging failures on feedstock

- docs/acknowledgments.rst
This PR has the objective of...
1. Improved the docs about user juarezr.
> added juarezr to acknowledgements

- docs/changes.rst
- petl/test/transform/test_reductions.py
- petl/transform/reductions.py
Implemented the feature requested in issue #370
> Allow specifying output field name for simple aggregation

- docs/changes.rst
- petl/test/transform/test_reductions.py
- petl/transform/reductions.py
Allow aggregation over the entire table (without a key)
> Aggregate with key is none

- .github/workflows/test-changes.yml
- requirements-database.txt
- requirements-formats.txt
- requirements-optional.txt
- requirements-tests.txt
- tox.ini
This PR added ci for testing petl on github actions on all push and pull_request.
This performs the same tests already executing on travis and appveyor:
- run nosetests testing for cases under test folder
- run nosetest with doctest for embedded tests
- run coverage tests with coveralls
- run sphinx docs testing
- run test on python versions 2.7 3.6 3.7 3.8 3.9
- run on linux and windows
Also some improvements:
- install dockers with postgresql and mysql for fromdb() todb() testing
- install docker with sftp and samba for testing remote files read/write
- run also on mac-os beyond ubuntu and windows
- increased the test span on python 2.7 and 3.9
- travis and appveyor still works
Caveats:
- bcolz fails to build on CI and is skipped
- doctest fails on some targes (works fully on python > …
> added ci for testing petl on github actions on all push and pull_request

- petl/transform/conversions.py
Fixes #542 
This PR has the objective of...giving an example of using a custom function with petl.transform.conversions.convert()
1. Improved the docs about...petl.transform.conversions.convert() providing example usage of custom function
> Document how to use convert with custom function

- petl/io/db.py
- petl/io/db_create.py
- petl/io/db_utils.py
- petl/test/io/test_db_server.py
This PR has the objective of fix issue with newer SQLAlchemy
1. Fixed a bug due to SQLAlchemy 1.4 removed/deprecated method `contextual_connect()`
> Fix #545 SQLAlchemy 1.4 removed/deprecated method

- .travis.yml
- requirements-formats.txt
- tox.ini
This PR has the objective of fixing travis-ci build failure on the deploy tag.
1. Added `python 3.9` for build on travis-ci
2. Put `python 2.7` bellow in the matrix list for avoiding failure while running `deploy` on a release tag `v#.#.#`
3. travis-ci will only trigger on main repo `github.com/petl-developers/petl`
4. Skip doctest with python3.9 for now
> travis: use python 3.6 on deploy

- docs/contributing.rst
This PR has the objective of...
1. fix instruction for sphinx install
2. fix sample tox run ( replace docstest with docs )
> Update contributing.rst instructions for local tests.

- petl/io/sources.py
- petl/test/io/test_avro.py
- petl/transform/basics.py
There are small typos in:
- petl/io/sources.py
- petl/test/io/test_avro.py
- petl/transform/basics.py
Fixes:
- Should read `dependencies` rather than `depedencies`.
- Should read `decompression` rather than `descompression`.
- Should read `current` rather than `curent`.
Closes #557
This PR has the objective of...
1. Added new `xyz` to...
2. Fixed a bug in...
3. Changed the behaviour of...
4. Improved the docs about...
> docs: fix a few simple typos

- petl/io/json.py
- petl/test/io/test_json.py
This PR has the objective of... being able to call header method when the table has been created with fromdicts
Originally reported here https://github.com/petl-developers/petl/issues/391
1. Renamed internal attribute header to _header so there is no conflict with the method with the same name.
> Fromdicts header does not raise

- petl/compat.py
- petl/test/test_comparison.py
This PR is a spin-off from #568 
1. Added Decimal to numeric types
2. Added a test case
Further changes are being considered with the impact on #563.
> Added Decimal to numeric types

- petl/test/transform/test_conversions.py
- petl/transform/conversions.py
> Fix convertall() when header line contain non-string values

- petl/io/pandas.py
Converting the table data to a list simply with list() causes the
table to be materialized three times because list() calls __len__()
on the table twice to populate the list.
Anyhow, there is no need to have the table data in a list when an
iteratotor can be passed to pandas.DataFrame.from_records().
Fixes #578.
> Fix todataframe() to do not iterate the table multiple times

- .github/workflows/test-changes.yml
- appveyor.yml
- petl/io/db.py
- petl/test/conftest.py
- petl/test/failonerror.py
- petl/test/helpers.py
- petl/test/io/test_avro.py
- petl/test/io/test_bcolz.py
- petl/test/io/test_db_create.py
- petl/test/io/test_db_server.py
- petl/test/io/test_numpy.py
- petl/test/io/test_pandas.py
- petl/test/io/test_pytables.py
- petl/test/io/test_remotes.py
- petl/test/io/test_whoosh.py
- petl/test/io/test_xls.py
- petl/test/io/test_xlsx.py
- petl/test/io/test_xml.py
- petl/test/transform/test_conversions.py
- petl/test/transform/test_intervals.py
- petl/test/transform/test_maps.py
- petl/test/transform/test_sorts.py
- petl/test/transform/test_validation.py
- pytest.ini
- requirements-tests.txt
- tox.ini
This PR has the objective of migrating the current nosetest runner to pytest.
Successfully ran the whole test suite against py3.8 with the exception of bcolz.
This the minimal effort and test suite code change required to use pytest.
1. The existing conditional checks have been rewritten / added to conform with pytest assertions
2. Expected exceptions rewritten to use `.raises`
3. Tests to be skipped are skipped using pytest 
4. Additionally a fix to close the opened connections in `_iter_sqlalchemy_engine` has been commited
> Migrate to pytest

- .vscode/launch.json
- .vscode/run_nose.py
- .vscode/settings.json
- .vscode/tasks.json
This PR has the objective of integrating recently migrated pytest into VSCode
1. Removed `nosetests` hacks
2. Enabled testing and debugging with pytest directly on VSCode
3. Added VSCode tasks for package build and install
Also:
- These changes only affect developers using VSCode.
- Detection is automatic when opening the local folder from the git clone
> Add support to testing and debugging with pytest on VSCode

- .github/workflows/test-changes.yml
This PR has the objective of testing compatibility with python 3.10.
1. Added a new matrix option to Github Action
2. Fixed a bug in...
3. Changed the behaviour of...
4. Improved the docs about...
> py3.10: start testing petl compatibility

- .github/workflows/test-changes.yml
- pytest.ini
- requirements-formats.txt
This PR has the objective of enabling doctests on python 3.9 and 3.10
1. Enabled doctests from python 3.6 to 3.10
2. Except on windows that doctests are enabled from python 3.8 to 3.10
- Before we cant do this because python3.10 is not compatible with `nosetests`.
- But after #584 was merged @arturponinski cleared this issue.
> ci: run full doctests from python 3.6 to 3.10

- .github/workflows/publish-release.yml
This PR has the objective of fixing the release to PyPI
1. Added new  workflow using Github Actions
2. The workflow will be triggered when publishing a new release on Github
3. This assumes that:
1.  The `master` branch has no issues and builds with no error
2. Testing and review of changes already happened using pull requests
3. Changes are documented in [docs/changes.rst](docs/changes.rst)
4. There is a summary of the changes in the release description
4. Only release to PyPI is tackled in this PR
5. Conda-Forge and readthedocs.org will be fixed further
6. Testing on PR does not apply. This workflow will be tested with the release `v1.7.6`
> cd: publish releases to PyPI with GA

- docs/changes.rst
This PR has the objective of aligning changes in the docs with github's releases page 
1. Improved the docs about changes.rst with missing releases
> Align docs changes with Github releases

- requirements-formats.txt
- requirements-tests.txt
- setup.py
This PR has the objective of keeping petl testing with updated packages
1. Removed upper limit on dependencies
2. Fix CVE-2021-33430
3. Announce python 3.9 in package
> ci: test with updated package versions

- README.rst
This PR has the objective of providing visibility to Conda Forge continuos delivery pipeline
1. Added new badge pointing to conda-forge/petl-feedstock automerge action status
2. Improved badges alt descriptions
3. Release v1.7.7 in [Conda Forge](https://anaconda.org/conda-forge/petl/1.7.7/download/noarch/petl-1.7.7-pyhd8ed1ab_0.tar.bz2)
> github: added a conda forge release status badge

- .vscode/settings.json
This PR has the objective of improving code analysis when using vscode
1. Configuring folders for vscode code analysis
2. Needs python extensions installed on vscode
3. Needs a python virtual environment with code analysis tools 
> vscode: enabe code analysis

- docs/changes.rst
- petl/comparison.py
- petl/test/transform/test_sorts.py
- petl/transform/sorts.py
This PR has the objective of fixing sorting of rows with different length. Closes https://github.com/petl-developers/petl/issues/385
1. Changed `comparable_itemgetter` to fallback to a custom implementation in case of `IndexError` and `KeyError`
> Fix sorting of rows with different length using custom itemgetter

- docs/changes.rst
This PR has the objective of supplementing `docs/changes.rst` with missing v1.7.8 entries
> Add missing v1.7.8 entries in changes.rst

- petl/test/helpers.py
- petl/test/io/test_xml.py
- petl/test/test_comparison.py
- petl/test/test_helpers.py
- petl/transform/regex.py
This PR has the objective of improving pytest helpers testing
1. Added new helper `get_env_vars_named` available for pytest for further use
2. Fixed a bug in test helper `ieq`
3. Fixed warnings in pytest of `xml` and `transform.regex.capture`
4. Improved the docs about test helper `ieq`, `eq_`
> Improve test helpers testing

- petl/io/csv.py
fromtsv() is a helper that calls fromcsv() with a different dialect set. However it was not passing on the header argument.
I apologize – I have not run unit tests, but the fix seems very straightforward and I figured a pull request was probably still more helpful than just raising a bug report.
> Fix fromtsv() to pass on header argument

- .gitignore
- docs/changes.rst
- petl/io/json.py
- petl/test/io/test_jsonl.py
This PR has the objective of adding support for writing to JSONL files
1. Updated tojson function in petl.io.json to write in JSONL format if `lines` argument is set to true
> Add Support for JSONL Writer

- .github/workflows/test-changes.yml
- docs/contributing.rst
- requirements-formats.txt
- requirements-optional.txt
- setup.py
- tox.ini
This PR has the objective of <describe here>
1. Added `python3.11` to the tox configuration
2. Added a new job in the github actions for testing `petL` with `python3.11` 
3. 
> Add python3.11 for the build and testing

- petl/io/sources.py
- petl/test/io/test_sources.py
This PR has the objective of fixing  #632.
1. Added a new test for checking output to stdout by default
2. Fixed the regression on all `to*()` functions
> Fix #632: calling functions to*() should output by default to stdout

- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-changes.yml
This PR has the objective of upgrading deprecated versions of github actions.
1. upgrade release to pypa/gh-action-pypi-publish@release/v1
2. upgrade to actions/setup-python@v4
3. upgrade to actions/checkout@main
> Gh actions upgrade

- petl/io/remotes.py
This PR fix the issue described in #646. In case a custom fsspec protocol is registered the "spec" is not of type dict. Implemented the suggested solution in #646 to check first if "spec" is of type dict.
> Fix in case a custom protocol was registered in fsspec 

- .github/workflows/test-changes.yml
This PR has the objective of fixing actions/setup-python#672.
1. python 2.7 not available on GitHub latest runners
2. python 3.6 not available on GitHub ubuntu-latest runner
> ci: workaround for actions/setup-python#672

- requirements-database.txt
- setup.py
This PR has the objective of restricting the maximum supported version of SQLAlchemy.
1. Added in requirements-database.txt: SQLAlchemy>=1.3.6,<2.0
2. Added in setup.py: SQLAlchemy>=1.3.6,<2.0
For SQLAlchemy >=2.0 check #648.
> ci: fix build as sqlalchemy is not supported yet

- docs/changes.rst
- petl/test/util/test_random.py
- petl/util/random.py
When calling randomtable without providing a seed, the warning `DeprecationWarning: Seeding based on hashing is deprecated since Python 3.9 and will be removed in a subsequent version. The only supported seed types are: None, int, float, str, bytes, and bytearray.` is emitted.
This actually becomes a TypeError in 3.11 and 3.12.
closes #657
It also seems like we don't even need to provide a seed based on the documentation, but I stuck to the way it was implemented before (using a hashed version of the date).
2.7: https://docs.python.org/2.7/library/random.html#random.seed
3.12: https://docs.python.org/3.12/library/random.html#random.seed
I also noticed that the filename utils/random.py seems to be conflicting with python's random module. When debugging the doctests in that file, I had to …
> Resolve DeprecationWarning: Seeding based on hashing

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- examples/notes/issue_219.py
- pyproject.toml
- requirements-linting.txt
This PR has the objective of improving lints and vscode settings.
1. Added configuration for bandit in pyproject.toml to reduce the CI source code analysis false positive (WIP)
2. Updated VS Code settings for python for working with newer versions
3. Added VS Code extension recommendations
4. Improved VS Code debug/launch tasks
5. Added requirements-linting.txt to easy linters installation
* [ X Testing guidelines:
> Chore: improve lints and vscode settings

- .github/workflows/test-changes.yml
- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- docker-compose.yml
- setup.py
- tox.ini
This PR has the objective of <describe it here>.
1. Added python 3.12 to CI testing on github actions
> feat(CI): add python 3.12 to CI testing on github actions

- .github/workflows/codacy-analysis.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-changes.yml
- petl/test/io/test_pytables.py
- requirements-formats.txt
- requirements-optional.txt
This PR has the objective of updating the Github actions.
1. upgrade actions for workflow
Use this checklist to ensure the quality of pull requests that include new code and changes to existing code.
> ci: upgrade versions of tools used in the Github Actions workflows

- .github/workflows/codacy-analysis.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-changes.yml
- requirements-formats.txt
This PR has the objective of avoiding double triggering of workflows
1. only trigger actions for code analysis workflows after testing changes
2. allow manual triggering of code analysis workflows
* [
> ci: only trigger actions for code analysis workflows after testing changes

- .github/workflows/codacy-analysis.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/test-changes.yml
- examples/notes/issue_219.py
This PR has the objective of <describe it here>.
1. add workflow_call to code analysis workflows
> ci: add workflow_call to code analysis workflows

- README.rst
This PR has the objective of <describe it here>.
1. Added PyPI downloads badge
> docs: added PyPI downloads badges

- .github/workflows/test-changes.yml
- examples/util/lookups.py
- petl/io/numpy.py
- petl/test/io/test_xml.py
- petl/util/lookups.py
- requirements-formats.txt
- requirements-optional.txt
- requirements-remote.txt
- requirements-tests.txt
- tox.ini
This PR aims to fix CI automated tests broken by the [end of support policy](https://github.com/actions/runner-images#support-policy) for the Python versions [2.7 up to 3.7](https://github.com/actions/runner-images/issues/6399).
The fix will require an upgrade to the [supported python versions](https://github.com/marketplace/actions/setup-python) in the latest version of [GitHub Actions Runner Images](https://github.com/actions/runner-images#available-images).
1. Added links to Github actions [setup-python](https://github.com/marketplace/actions/setup-python) and [runner-images](https://github.com/actions/runner-images#available-images)
2. Avoid failures due to unsupported Python versions in the CI [test-changes](https://github.com/petl-developers/petl/actions/workflows/test-changes.yml) …
> Upgrade Python versions supported by setup-python and runner-images on Github Actions

- docs/changes.rst
- petl/test/transform/test_joins.py
- petl/transform/hashjoins.py
- petl/transform/joins.py
This PR has the objective of the bug in joins and hashjoins when tables with uneven rows were joined, data was put in incorrect columns. Issue is similar to the one reported here #176.
* Added `stack` to square up tables before join.  
> Fix: Joining tables with uneven rows gives wrong result.
