petl-developers/petl

petl/util/base.py
Changed use of str() with text_type() in fieldnames() and asdict()
=> Resolves #350

petl/io/sources.py, petl/test/io/test_sources.py
MemorySource is behaving as expected I believe, needs to be passed bytes not text.
=> resolves #323 with documentation and extra test

optional_requirements.txt, petl/io/xlsx.py
This addresses issue #393 by changing the way in which xlsx imports and exports occur.
=> Resolves #393: update toxlsx and XLSXView for openpyxl 2.4.0 compatibility

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, docs/contributing.rst, docs/intro.rst, tox.ini
This PR adds github templates for issues and PRs, and some guidance for core devs re merging PRs.
Also a minor fix for Travis, and resolves #452.
=> DOC: information re contributing

docs/changes.rst, petl/io/xls.py, petl/io/xlsx.py
Adapted from #470. Resolves #469.
=> Passing along **kwargs to xlrd

docs/changes.rst, docs/io.rst, docs/transform.rst, docs/util.rst, petl/io/xlsx.py, petl/test/io/test_xlsx.py, petl/util/timing.py
Based on #424, this PR adds tests and deals with table headers.
=> Append xlsx

docs/changes.rst, petl/util/timing.py, tox.ini
* Simplify tox.ini.
* Add release notes for #414.
=> Maintenance: simplify tox; release notes

.travis.yml
Adds PYPI deployment to travis config.
=> Add pypi deploy

petl/util/base.py
=> Fix deprecation warnings due to invalid escape sequences.

petl/io/db.py
This change implements the solution given in #427
=> Implement the change shown in #427

petl/io/avro.py, petl/test/io/test_avro.py, petl/test/io/test_avro_schemas.py
This PR fixes a bug while writing avro files.
1. Fixed `bool` columns detected as `int`
2. Added `bool` columns for testing in CI
=> fix boolean type detection in toavro

docs/changes.rst
This PR has the objective of updating changes for release
1. updated chages.rst for 1.6.2
=> updated chages.rst for 1.6.2

docs/changes.rst
This PR has the objective of preparing release 1.6.3
1. updated chages.rst for 1.6.3
=> updated chages.rst for 1.6.3

docs/changes.rst, petl/io/json.py, petl/test/io/test_jsonl.py
1. Added JSON lines support https://jsonlines.org/examples/
=> JSONL Support Added

petl/test/io/test_remotes.py
This PR has the objective of fixing a false positive in CodeQL analysis.
1. Fixed a false positive in CodeQL analysis due to printing user/password in a sintetic test.
=> fix CodeQL false positive

docs/acknowledgments.rst
=> Added My Name In Acks - Supported JSONL

petl/util/base.py
This should also bring a minor performance gain.
=> Minor modernization

.github/workflows/test-changes.yml, pytest.ini, requirements-formats.txt, tox.ini
Follow up of https://github.com/petl-developers/petl/pull/590 to run git actions
=> Py3 10full

.github/PULL_REQUEST_TEMPLATE.md, README.rst
This PR has the objective of updating GitHub docs reflecting ci migration.
1. Added new CI/CD badges
2. Updated PR template
Checklist for pull requests including new code and/or changes to existing code.
=> GitHub pr template

.github/workflows/test-changes.yml, requirements-tests.txt
This PR has the objective of locking pytest at version 6.*
=> Lock pytest at version prior to 7

petl/test/io/test_html.py
This PR has the objective of <describe here>
1. Added a new test to `tohtml` testing CSS styles
=> pytest: test tohtml with css styles

docs/index.rst, docs/io.rst, docs/transform.rst
This PR has the objective of <describe here>
1. Reorganized IO topics in docs
2. Some improvement to docs
=> docs: improve io topic organization

docs/io.rst, petl/io/__init__.py, petl/io/avro.py, petl/io/gsheet.py, petl/test/io/test_gsheet.py, requirements-formats.txt
This PR has the objective of adding support to [Google Sheets](https://docs.gspread.org/en/latest/index.html)
1. Refactored #405
2. Renamed to/from-gsheet parameters.
3. Upgraded [gspread](https://docs.gspread.org/en/latest/index.html) support from v0.8 to v5.5
4. Improved the docs about the gsheet
- CI needs a GCP account/Project
- May decrease coverage because of missing CI configuation
=> Add improved support for working with Google Sheets

docs/related_work.rst
This PR has the objective of adding links to related work.
1. Improved the docs about related work.
Validated changed file as valid RST.
=> Add reference to Tablib

.github/PULL_REQUEST_TEMPLATE.md, docs/changes.rst
This PR has the objective of preparing a new release.
1. Updated changelog for v1.7.13
2. Fixed pull request template spelling
=> Update changelog for v1.7.13

docs/changes.rst
This PR has the objective of updating the changelog to version 1.7.12
1. Update the changelog to version 1.7.12
2. Previously was mistakenly 1.7.13...
=> Update the changelog to version 1.7.12

.github/workflows/codeql-analysis.yml
This PR has the objective of <describe it here>.
1. Upgraded deprecated version of action
2. 
=> ci: upgrade codeql to v2

docs/changes.rst
This PR has the objective of preparing the release  `v.7.14`.
1. doc: update changes for v.7.14
=> doc: update changes for v.7.14

docs/changes.rst, docs/contributing.rst, docs/install.rst, setup.py
This PR has the objective of updating the documentation to release 1.7.16.
=> Prepare for release1.7.16

.readthedocs.yaml
This PR has the objective of fix docs build failure at readthedocs.
=> ci: fix docs build failure at readthedocs

.github/workflows/codacy-analysis.yml, docs/changes.rst, petl/io/csv_py2.py, petl/util/base.py, pyproject.toml
This PR aims to reduce comments generated by code scanning in PRs.
1. Added settings for reducing codacity and codeql lints
3. Fixed a warning in github/codeql-action/upload-sarif
=> Chore/reduce linting due to outdated code style assigned to be refactored/reformated before v2.0

.github/workflows/codacy-analysis.yml, .github/workflows/codeql-analysis.yml, .github/workflows/test-changes.yml, .vscode/extensions.json
This PR has the objective of  fix CI workflows.
1. Added trigger on merge_group for workflows
2. Fixed the codacy action
3. Updated vscode extension recommendations
=> Fix/ci codacy Action
